//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 02:55:10 PM GMT 
//


package Examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GeniusAppt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeniusAppt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="problem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="appdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="apptime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

//SHOULD ADD DETAILS OF CUSTOMER TO GENIUS BAR APPOINTMENT !! <<<<<<<<<<<<

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeniusAppt", propOrder = {
    "problem",
    "appdate",
    "apptime"
})
public class GeniusAppt {

    @XmlElement(required = true)
    protected String problem;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appdate;
    @XmlElement(required = true)
    protected String apptime;

    /**
     * Gets the value of the problem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProblem() {
        return problem;
    }

    /**
     * Sets the value of the problem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProblem(String value) {
        this.problem = value;
    }

    /**
     * Gets the value of the appdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppdate() {
        return appdate;
    }

    /**
     * Sets the value of the appdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppdate(XMLGregorianCalendar value) {
        this.appdate = value;
    }

    /**
     * Gets the value of the apptime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApptime() {
        return apptime;
    }

    /**
     * Sets the value of the apptime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApptime(String value) {
        this.apptime = value;
    }

}
